### ISSUE TITLE
Encoders/Decoders should not be implicit

### ISSUE THREAD

**Issue by tonymorris** [zio/zio-json#1]
These should not be type-classes, but data types.

See https://github.com/qfpl/waargonaut for a JSON library that fixes many of the errors of argonaut and subsequent JSON libraries in Scala.

**Comment by fommil** [comment]
Yeah, I hear you man... that was the original design. The reason I didn't do it that way is because nobody has written a boilerplate generation tool for records of functions in Scala; I have plans to write one for Haskell (see https://gist.github.com/fommil/6e8ca075644a4f26033e74f39ca6ee54) but it's not something I would want to write in Scala for fun: it would ruin too many fantastic days.

TL;DR I did it this way only because Magnolia exists and it uses implicits. You can always use non-implicit decoders if you want... these ones are not automatically generated for ADTs, unlike how other libraries work. The `Decoder` can have a `MonadError String` and the `Encoder` (not written yet) can have a `Divisible`, but to avoid dependencies I just hardcoded the scalaz type signatures onto the trait to allow manual derivation of that nature.

Also, I don't really subscribe to the belief that `implicit` implies that something is necessarilly a typeclass (in the Haskell sense) in Scala... it's really being used here as a wiring mechanism because there isn't a decent alternative, and inference is bad; I'm not claiming any laws, and I'm definitely not guaranteeing global coherence.

**Comment by fommil** [comment]
you funny fucker, Tony :rofl:
