### ISSUE TITLE
Unable to locate the JsonDecoder for a type constructor containing a nested type.

### ISSUE THREAD

**Issue by wi101** [zio/zio-json#1128]
Hello,

This issue appeared when updating to zio-json: `0.7.0`. 
Here is an example:
```scala

final case class Id[A](value: A)
object Id {
  implicit def decoder[A: JsonDecoder]: JsonDecoder[Id[A]] = DeriveJsonDecoder.gen[Id[A]]
}

final case class Person(name: String) extends AnyVal
object Person {
  implicit val decoder: JsonDecoder[Person] = DeriveJsonDecoder.gen
}


final case class People(ids: Id[Person])
object People {
  implicit val decoder: JsonDecoder[People] = DeriveJsonDecoder.gen
}
```

Error:

```
magnolia: could not find JsonDecoder.Typeclass for type Id[Person]
[error]     in parameter 'ids' of product type People
[error]   implicit val decoder: JsonDecoder[People] = DeriveJsonDecoder.gen
```

`People.decoder` cannot find the decoder for `Id[Person]`.
There is an issue on finding the `Id.decoder` ..

when we manually add the decoder to `Id` companion object:
```scala
object Id {
    implicit val decoderIds: JsonDecoder[Id[Person]] = DeriveJsonDecoder.gen
}
```
The same error appears. But it works only when we add that decoder to `People` companion. 
```scala
object People {
  implicit val decoderIds: JsonDecoder[Id[Person]] = Id.decoder
  implicit val decoder: JsonDecoder[People] = DeriveJsonDecoder.gen
}
```

**Comment by Anshgrover23** [comment]
/attempt #1128

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxynj6pi000al409csvai8a3/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by 987Nabil** [comment]
@wi101 I am unable to reproduce What Scala version are you using? Are the definitions all in the same file? Are you sure you have no conflicting versions in your project?

**Comment by omarnagy91** [comment]
attempt #1128

**Comment by wi101** [comment]
@987Nabil

This is the full example (the same file)
```scala
import zio.json.{DeriveJsonDecoder, JsonDecoder}

final case class Id[A](value: A)
object Id {
  implicit def decoder[A: JsonDecoder]: JsonDecoder[Id[A]] = DeriveJsonDecoder.gen[Id[A]]
}

final case class Person(name: String) extends AnyVal
object Person {
  implicit val decoder: JsonDecoder[Person] = DeriveJsonDecoder.gen
}


final case class People(ids: Id[Person])
object People {
  implicit val decoder: JsonDecoder[People] = DeriveJsonDecoder.gen
}
```

`scalaVersion: 2.13.14` 
`zioJsonVersion: 0.7.0`

**Comment by TintinSDev** [comment]
Let's solve this. Will be pushing the solution in few

**Comment by ifndev** [comment]
Hi, this issue seems stale so I gave it a shot.

## What I found out:

- PR #1115 introduced "codec derivation for types that already have encoder and decoder"
- Faced with an error in one of the tests (same test case as this issue) with scala 2.12, it was decided to remove the feature for this specific version.
- Turns out it doesn't work on 2.13 either

## What I did:

- I reverted the VersionSpecific code as it did not fix the issue
- I identified the problematic line
    https://github.com/zio/zio-json/blob/6d2abd46385af7002b193d52d19f49dbc42e0d01/zio-json/shared/src/main/scala-2.13/zio/json/JsonCodecVersionSpecific.scala#L5
- As I couldn't find a reason for the 'encoder' parameter being implicit, and found no test cases justifying it, i made it explicit again
- Tests now passes on all Scala versions
- Code provided by @wi101 compiles successfully
- PR yet to be submitted...

/attempt #1128

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ifndev) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ifndev | 1 bounty from 1 project | <div align="center">Python, C++, <br />TypeScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxynj6pi000al409csvai8a3/cancel-attempt) |

**Comment by ifndev** [comment]
Just submitted PR #1139

It's based on the assumption that making the 'encoder' parameter implicit was a mistake, so it may be wrong. 
Ideally, adding a test for a specific case covered by PR #1115 would be a good idea.

Let me know if I missed something :)

**Comment by Not-Aru** [comment]
Hey, when can we expect the PR to be merged? I am working on an implementation that depends on this fix.
