### ISSUE TITLE
Add helper methods in zio.json package object to read / write from URLs / files

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-json#59]
```scala
sealed trait JsonStreamDelimiter
object JsonStreamDelimiter{
  case object Newline extends JsonStreamDelimiter
  case object Array extends JsonStreamDelimiter
}
```

```scala
def readJson(url: URL, jsonDelimiter: JsonStreamDelimiter = JsonStreamDeliminter.Newline): ZStream[Blocking, IOException, Json]
def readJson(file: String, jsonDelimiter: JsonStreamDelimiter = JsonStreamDeliminter.Newline): ZStream[Blocking, IOException, Json]
def readJson(file: Path, jsonDelimiter: JsonStreamDelimiter = JsonStreamDeliminter.Newline): ZStream[Blocking, IOException, Json]
def readJson(file: java.io.File, jsonDelimiter: JsonStreamDelimiter = JsonStreamDeliminter.Newline): ZStream[Blocking, IOException, Json]
```

```scala
def writeJson(file: String, stream: ZStream[Blocking, IOException, Json], jsonDelimiter: JsonStreamDelimiter = JsonStreamDeliminter.Newline): ZIO[Blocking, IOException, Unit]
def writeJson(file: Path, stream: ZStream[Blocking, IOException, Json], jsonDelimiter: JsonStreamDelimiter = JsonStreamDeliminter.Newline): ZIO[Blocking, IOException, Unit]
def writeJson(file: java.io.File, stream: ZStream[Blocking, IOException, Json], jsonDelimiter: JsonStreamDelimiter = JsonStreamDeliminter.Newline): ZIO[Blocking, IOException, Unit]
```

**Comment by fsvehla** [comment]
I'll take this.

**Comment by jdegoes** [comment]
@fsvehla Awesome.

Maybe it would be good to have `readJsonAll` variants that call `runCollect` on the stream variations.

We should also think about the decoding version of these: even though it's only a few lines, it's best if users don't have to interact with the transducers directly.

Maybe something like `readJsonAs[Person](...)`, `writeJsonAs[Person](...)` for `case class Person()`.

**Comment by fsvehla** [comment]
Because of multiple overloaded methods with default arguments we can’t specify the default of `NewLine`.

We could simply introduce multiple methods like `readJsonFile`, `readJsonUrl`, etc, but
this got me thinking and I think that JSON lines will be used in the vast majority of use cases - it is very common in ETL processes / as a logging format etc, while I’ve never seen array delimiters in the wild.

I propose providing only `def readJsonLines`, `writeJsonLines` here.

@jdegoes wdyt?
